### ISSUE TITLE
Failed to implement errors

### ISSUE THREAD

**Issue by jasonfine** [increments/graphql-kaminari_connection#2]
With the following query

```query ($page: Int, $per: Int) {
  bars(page: $page, per: $per) {
    pageData {
      currentPage
      isFirstPage
      isLastPage
      isOutOfRange
      limitValue
      nextPage
      prevPage
      totalPages
    }
    items {
      fullName
    }
  }
}
```
Seeing both 

`Failed to implement BarPage.pageData` and
`Failed to implement BarPage.items` 

after following the usage instructions, furthermore, when i dump the schema, it appears to have added things:

`bars(page: Int, per: Int): BarPage!`

```"""
Autogenerated page type for BarPage
"""
type BarPage {
  """
  A list of items
  """
  items: [Bar!]!
  pageData: PageData!
}```

Any ideas what's missing?

**Comment by AlinGhinoiu** [comment]
This PR fixed it https://github.com/increments/graphql-kaminari_connection/pull/3
